---
title: "Data Science"
author: "The Focal Point"
date: "`r Sys.Date()`"
output:
    revealjs::revealjs_presentation:
      navigationMode: linear
      theme: league
      highlight: zenburn
      footer: "The Focal Point (2023)"
      transition: "slide"
      center: true
      css: style.css
---

```{r setup, include=FALSE}
# Templates : https://codingclubuc3m.rbind.io/post/2019-09-24/
# RevealJS Docs : https://revealjs.com/themes/

knitr::opts_chunk$set(echo = FALSE)
if (packageVersion('rmarkdown') <= '1.9') {
  install.packages('rmarkdown')  # update rmarkdown from CRAN
}
if (packageVersion('revealjs') <= '0.8') {
  install.packages('revealjs')  # update rmarkdown from CRAN
}
```

```{r echo=FALSE, results='hide', message=FALSE}
library(stringr)
library(ggplot2)
library(lubridate)
library(dplyr)
library(scales)
library(corrplot)
library(plotly)
library(knitr)

options("scipen"=100, digits = 22)
```

# Background

```{r child='./slides/Background/Background.Rmd', cache=TRUE}
```

# Data Collection

```{r, echo=FALSE, results='hide', cache=TRUE}
data <- read.csv(file='./dataset.csv', stringsAsFactors = TRUE)
```

```{r, cache=TRUE}
str(data)
```

# Data Preparation & Cleaning

## What is Data Preparation & Cleaning?

-   Ensuring data integrity, accurate reports

-   Fixing missing values, outliers, noise

```{r child='./slides/DataPreparation/DataPreparation.Rmd', cache=TRUE}
```

# Data Analysis

-   Observation

-   Insights

```{r child='./slides/DataAnalysis/DataAnalysis.Rmd', cache=TRUE}
```

# Credit Risk Score

-   The Bank wants to launch a new loan product to target persons who may be considered to have the least credit risk
-   5 C's of Credit

------------------------------------------------------------------------

```{r child='./slides/DataAnalysis/analytics/h_creditRisk.Rmd'}
```
