### Jobs & Deposits

```{r echo=FALSE}
options(digits=1)
avg_job_deposit <- aggregate(deposit ~ job, data, mean, na.rm = TRUE)
avg_job_deposit$deposit <- round(avg_job_deposit$deposit,2)
```

------------------------------------------------------------------------

### Jobs & Deposits

```{r echo=FALSE}
 
# Plotting the average deposits
ggplot(avg_job_deposit, aes(x = job, y = deposit,label=deposit)) +
  geom_bar(stat = "identity", fill = "blue") +
  geom_bar(data = subset(avg_job_deposit, deposit == max(deposit)), fill = "red", stat = "identity")+
  geom_bar(data = subset(avg_job_deposit, deposit == min(deposit)), fill = "black", stat = "identity")+
  geom_text(size = 3, position = position_stack(vjust=1.08)) +
  xlab("Job") +
  ylab("Average Deposit") +
  ggtitle("Average Deposits by Job Category")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

------------------------------------------------------------------------

## Summary of Findings

-   Job with **minimum** deposit: **Housemaid**

-   Job with **maximum** deposit: **Self-employed**
