<h3>Gathering Information on Individuals Loans</h3>

```{r echo=TRUE}

mortgage.personal <- nrow(data
[data$housing == 'yes' & data$loan == 'yes',])

one.loan <- nrow(data[xor(data$housing == 'yes', 
data$loan == 'yes'),])

no.loan <- nrow(data[data$housing == 'no' & data$loan == 'no',])

```
### Loan Distribution Table
```{r echo=FALSE, results='asis'}
# Create a data frame with the category names and counts
table_data <- data.frame(Category = c("Both Loans", "One Loan", "No Loan"),
                         Count = c(mortgage.personal, one.loan, no.loan))

# Generate the table using kable()
table_output <- kable(table_data, format = "markdown", col.names = c("Category", "Count"))

# Print the table
print(table_output)
#table_data
```
------------------------------------------------------------------------

<h3>Presenting Loan Information</h3>

```{r echo=FALSE}
chart.data <- c(mortgage.personal,one.loan,no.loan )

piepercent<- paste0(round(100*chart.data/sum(chart.data), 0),"%")

labels <- c("Both_Loans", "OneLoan", "NoLoan")

pie(chart.data, labels = piepercent,
    main = "Loan Pie Chart", col = rainbow(length(chart.data)))
legend("topright", c("Both Loans", "One Loan", "No Loan"),
       cex = 0.5, fill = rainbow(length(chart.data)))
```
