- Data Type: Quantitative

- Measurement: Ratio

```{r echo=FALSE}
str(data$balance)
options(digits = 1)
summary(data$balance)
options(digits = 22)

```

------------------------------------------------------------------------

```{r echo = FALSE}
balancePreClean <- data$balance
hist(balancePreClean,main="Histogram of Balance Before Cleaning")
```

------------------------------------------------------------------------

```{r}
d <- density(balancePreClean,na.rm = T)
plot(d,frame=FALSE, col = "Blue",main="Density of Balance Before Cleaning")
```

------------------------------------------------------------------------

```{r}
boxplot(balancePreClean,main="Boxplot of Balance Before Cleaning")
```

------------------------------------------------------------------------

```{r echo=TRUE}
data$old.balance <- data$balance
avg.job.balance <- aggregate(balance ~ job, data, mean, na.rm = TRUE)
data$avg.balance <- avg.job.balance$balance[match(data$job, avg.job.balance$job)]
#Replace balance with average balance based on job if the balance is over the 75% quartile, because we don't want to affect more than 10% of the value
#and we would not be affecting up to 10% when we change outliers using this method
data$balance <- ifelse(data$balance > 500000, as.integer(data$avg.balance), data$balance)
data$new.balance <- data$balance
data$ratio <- percent((data$new.balance- data$old.balance)/data$old.balance)
data <- data %>% mutate(ratio = (old.balance- new.balance) / old.balance,
                        percentage = percent(ratio),
                        new.deposit = ifelse(ratio == 0, deposit, deposit * (1-ratio)))

data[is.na(data)] <- 0
data$balance <- ifelse(data$balance<=-112000, -112000, data$balance)

```

------------------------------------------------------------------------

```{r echo = TRUE}
#After Cleaning
data$new.balance <- NULL
data$old.balance <- NULL
data$ratio <- NULL
data$percentage <- NULL
data$avg.balance <- NULL
data$deposit <- data$new.deposit
data$new.deposit <- NULL
avg.job.balance <- NULL

```

------------------------------------------------------------------------

```{r}
hist(data$balance,main = "Histogram of Balance After Cleaning")
```

------------------------------------------------------------------------

```{r}
plot(density(data$balance),main = "Density of Balance After Cleaning")

```

------------------------------------------------------------------------

```{r}
boxplot(data$balance,main="Box Plot of Balance After Cleaning")

```

------------------------------------------------------------------------

```{r}
hist(data$deposit,main = "Histogram of Deposit After Accounting for Balance")
```

------------------------------------------------------------------------

```{r}
plot(density(data$deposit),main = "Density of Deposit After Accounting for Balance")

```

------------------------------------------------------------------------

```{r}
boxplot(data$deposit,main="Box Plot of Deposit After Accounting for Balance")

```

