------------------------------------------------------------------------

### Normalizing Balance

```{r echo = TRUE, eval=FALSE}


min.balance <- min(data$balance, na.rm = T) # Setting Min Value
max.balance <- max(data$balance, na.rm = T) # Setting Max value

# Original 252
new.min <- as.integer(min.balance/1000) # Setting new min value for normalized Data to -112
new.max <- as.integer(max.balance/1000) # Setting new max value for normalized Data to 669


#Normalization Based on Formula
data<- data %>% 
  mutate(balance = as.integer(
    ((balance - min.balance)/(max.balance - min.balance ) 
     * (new.max - new.min) + new.min)
    )
  )

```

------------------------------------------------------------------------

```{r fig.height=24, fig.width=24, figures-side, fig.show="hold", out.width="45%"}
#Before Normalization
avgBalancePerJob <- setNames(
  aggregate(
    data$balance, 
    list(data$job), 
    FUN = mean, 
    na.rm = TRUE
    ),
    c("Job","Balance")
  )
avgBalancePerJob$Balance <- round(avgBalancePerJob$Balance, 0)

colors <- c("red", "blue", "green", "orange", "purple", "pink", "brown", "gray", "yellow", "cyan", "magenta", "darkgreen", "darkblue", "darkred")

ggplot(avgBalancePerJob, aes(x = Job, y = Balance, fill = Job)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "", title = "Mean by Job After Normalization") +
  theme(panel.background = element_blank(),panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 40),
        axis.text.y = element_text(size = 40),
        axis.title.x.top = element_text(size = 40),
        legend.text = element_text(size = 50),  # Adjust legend text size
        legend.title = element_text(size = 50) ) +
  scale_fill_manual(values = colors)

#Normalization
min.balance <- min(data$balance, na.rm = T) # Setting Min Value
max.balance <- max(data$balance, na.rm = T) # Setting Max value

# Original 252
new.min <- as.integer(min.balance/1000) # Setting new min value for normalized Data to -112
new.max <- as.integer(max.balance/1000) # Setting new max value for normalized Data to 669


#Normalization Based on Formula
data<- data %>% 
  mutate(balance = as.integer(
    ((balance - min.balance)/(max.balance - min.balance ) * (new.max - new.min) + new.min)
    )
  )

#After Normalization
avgBalancePerJob <- setNames(
  aggregate(
    data$balance, 
    list(data$job), 
    FUN = mean, 
    na.rm = TRUE
    ),
    c("Job","Balance")
  )
avgBalancePerJob$Balance <- round(avgBalancePerJob$Balance, 0)



# Assuming "avgBalancePerJob" is your data frame with columns "Job" and "Balance"

# Define the colors for each job category


ggplot(avgBalancePerJob, aes(x = Job, y = Balance, fill = Job)) +
  geom_bar(stat = "identity") +
  labs(x = "", y = "", title = "Mean by Job After Normalization") +
  theme(panel.background = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1,size = 24)) +
  scale_fill_manual(values = colors)

```

\

```{r}
#barplot(table(data$job), xlab = "", ylab = "", main = "Job Count", las=2, cex.names = 0.8)
```

------------------------------------------------------------------------
