- Data Type: Quantitative

- Measurement: Ratio

```{r echo=FALSE}
str(data$deposit)
options(digits = 1)
summary(data$deposit)
options(digits = 22)

```

------------------------------------------------------------------------

```{r echo = FALSE}
depositPreClean <- data$deposit
hist(depositPreClean,main="Histogram of Deposit Before Cleaning")
```

------------------------------------------------------------------------

```{r}
d <- density(depositPreClean,na.rm = T)
plot(d,frame=FALSE, col = "Blue",main="Density of Deposit Before Cleaning")

```

------------------------------------------------------------------------

```{r}
boxplot(depositPreClean,main="Box Plot of Deposit Before Cleaning")
```

------------------------------------------------------------------------

```{r echo=TRUE}
avg.job.deposit <- aggregate(deposit ~ job, data, mean, na.rm = TRUE)

data$avg.deposit <- avg.job.deposit$deposit[match(data$job, 
                                                  avg.job.deposit$job)]

data$deposit <- ifelse(is.na(data$deposit), 
                       round(data$avg.deposit,1), 
                       round(data$deposit,1))

data$deposit <- ifelse(data$deposit>100000, 100000, data$deposit)
```

------------------------------------------------------------------------

```{r echo = TRUE}
#After Cleaning
data$avg.deposit <- NULL
avg.job.deposit <- NULL
avg.job.balance <- NULL
d <- NULL
```

------------------------------------------------------------------------

```{r}
hist(data$deposit,main = "Histogram of Deposit After Cleaning")
```

------------------------------------------------------------------------

```{r}
plot(density(data$deposit),main = "Density Plot of Deposit After Cleaning")

```

------------------------------------------------------------------------

```{r}
boxplot(data$deposit,main="Box Plot of Deposit After Cleaning")

```
