------------------------------------------------------------------------

### Duration Preparation

-   This feature shows the time spent (seconds) on the last call.

-   Measurement: Quantitative (Interval)

-   Data type: Numeric

```{r echo=FALSE}
#view the structure of the duration column 
#str(data$duration)
```

```{r echo=TRUE}
#view the summary of the duration column 
summary(data$duration)
```

------------------------------------------------------------------------

### Preparation of Duration

#### Checking for NA and NULL values

```{r echo=TRUE}
#find the sum of NA values 
dur_na_sum <- sum(is.na(data$duration))
print(dur_na_sum)

#find the sum of null values 
dur_null_sum <- sum(is.null(data$duration))
print(dur_null_sum)
```

------------------------------------------------------------------------

### Preparation of Duration

#### conversion from SECONDS to MINUTES

```{r echo=TRUE}
#install.packages("lubridate")
   
#convert from seconds to minutes
data$duration_temp <- round(as.duration(data$duration) / dminutes(1))
data$duration <- round(as.duration(data$duration) / dminutes(1))
```

```{r echo=FALSE}
data$duration_before <- data$duration
data$duration <- data$duration_temp

data$duration <- ifelse(data$duration>12, mean(data$duration), data$duration)
```

------------------------------------------------------------------------

### Visualization of Duration

::: {style="display: flex;"}
<div>

```{r echo=FALSE}
Duration <- data$duration_before
duration.hist_before <- hist(data$duration_before, main = 'Histogram of Duration (before cleaning)')
```

</div>

<div>

```{r echo=FALSE}
Duration <- data$duration
duration.hist_after <- hist(Duration,main = 'Histogram of Duration (after cleaning and conversion)')
```

</div>
:::

------------------------------------------------------------------------

### Visualization of Duration

::: {style="display: flex;"}
<div>

```{r echo=FALSE}

#density plot for alternate visualization
Duration <- data$duration_before
d_before <- density(data$duration_before,na.rm = T)
plot(d_before,frame=FALSE, col = "Blue",main = 'Density plot of Duration (before cleaning)')
```

</div>

<div>

```{r echo=FALSE}

d_after <- density(data$duration,na.rm = T)
plot(d_after,frame=FALSE, col = "Blue",main = 'Histogram of Duration (after cleaning and conversion)')
```

</div>
:::

------------------------------------------------------------------------

### Summary of Duration

```{r echo=TRUE}
avg_duration <- mean(data$duration)
avg_duration <- round(avg_duration,2)
print(avg_duration)
```

------------------------------------------------------------------------
