## Month Preparation

This feature indicates the last deposit month of the year for the customer

Measurement: Quantitative (Categorical)

Data type: Factor

```{r echo=TRUE}
#view the structure of the duration column  
str(data$month)
```

------------------------------------------------------------------------

### Summary of Month Data

```{r echo=TRUE}
#view the structure of the duration column  
summary(data$month)
```

-   Pre-clean Checks

    ```{r echo=TRUE}
    #find the sum of NA values  
    month_na_sum <- sum(is.na(data$month))
    print(month_na_sum)
    ```

    ```{r echo=TRUE}
    #find the sum of null values  
    month_null_sum <- sum(is.null(data$month))
    print(month_null_sum)
    ```

    ------------------------------------------------------------------------

    ### Summary of Month Data

    ```{r echo=TRUE}
    #create a list of valid months
    valid_months <- tolower(month.name)

    #check if any months are invalid
    invalid_months <- !(tolower(data$month) %in% valid_months)
    num_of_invalid <- sum(invalid_months)
    ```

------------------------------------------------------------------------

## Visualization of Months

-   Bar graph

    -    used to show distribution blah blah

```{r echo=TRUE}
library(ggplot2)

sum_deposits_per_month <- aggregate(deposit ~ month, data, sum)

ggplot(sum_deposits_per_month, aes(x = month, y = deposit, label=deposit)) +
  geom_bar(stat = "identity", fill = "blue") +
  geom_bar(data = subset(sum_deposits_per_month, deposit == max(deposit)), fill = "red", stat = "identity")+
  geom_text(size = 3, position = position_stack(vjust=1.02)) +
  xlab("Months") +
  ylab("Amount of Deposits") +
  ggtitle("Amount of Deposits per month") +
  theme(plot.title = element_text(hjust = 0.5))
```
